
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1

kind: Deployment
metadata:
  name: msr-deployment
  namespace: default
  labels:
   app: msr-customer
spec:
  replicas: 1 # tells deployment to run 1 pod matching the template
  selector:
    matchLabels:
      app: msr-customer
  template: # create pods using pod definition in this template
    metadata:
        labels:
          app: msr-customer
    spec:
      containers:      
      - env:
        - name: SAG_IS_CONFIG_PROPERTIES
          value: /opt/softwareag/msr-config/configuration
        name: customer-ismicroservicesruntime        
        image: docker.io/pbrosi/is:CUST
        imagePullPolicy: IfNotPresent        
        ports:
        - containerPort: 5555
        volumeMounts:
        - mountPath: /opt/softwareag/msr-config
          name: vol-cz6z7
      volumes:
      - configMap:
          defaultMode: 420
          name: msr-config
          optional: false
        name: vol-cz6z7

---
kind: Service
apiVersion: v1	
metadata:
  name: msr-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: msr-customer
  ports:
  - protocol: TCP
    port: 5555
    targetPort: 5555
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: msr-ingress
  labels:
    {}
  namespace: default
spec:
  defaultBackend:
    service:
      name: msr-service
      port:
        number: 5555
  rules:
    - host: msr-ep.192.168.26.132.sslip.io
      http:
        paths:
          - backend:
              service:
                port:
                  number: 5555
                name: msr-service
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - msr-ep.192.168.26.132.sslip.io
